version: '3'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "3306:3306"
  app:
    container_name: afiliados-api
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "--timeout=30", "db:3306", "--", "npm", "start"]